# Generated by Django 6.1.1 on 2026-09-15 14:33

from django.db import migrations

SEED_CATEGORIES = [
    ("Cereals", "cereals"),
    ("Legumes", "legumes"),
    ("Fruits", "fruits"),
    ("Vegetables", "vegetables"),
    ("Roots and tubers", "roots-and-tubers"),
    ("Coffee", "coffee"),
    ("Livestock", "livestock"),
    ("Other agricultural products", "other-agricultural-products"),
]


def seed_categories(apps, schema_editor):
    """Create the initial produce categories."""
    ProduceCategory = apps.get_model("marketplace", "ProduceCategory")
    ProduceCategory.objects.bulk_create(
        ProduceCategory(name=name, slug=slug) for name, slug in SEED_CATEGORIES
    )


def unseed_categories(apps, schema_editor):
    """Remove the seeded produce categories."""
    ProduceCategory = apps.get_model("marketplace", "ProduceCategory")
    ProduceCategory.objects.filter(slug__in=[slug for _, slug in SEED_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
