# Generated by Django 6.1.1 on 2026-09-10 22:26

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('crop_type', models.CharField(choices=[('maize', 'Maize'), ('beans', 'Beans'), ('coffee', 'Coffee'), ('matooke', 'Matooke'), ('groundnuts', 'Groundnuts'), ('millet', 'Millet'), ('rice', 'Rice'), ('cassava', 'Cassava'), ('sweet_potato', 'Sweet potato'), ('irish_potato', 'Irish potato'), ('sunflower', 'Sunflower'), ('sesame', 'Sesame'), ('sorghum', 'Sorghum'), ('horticulture', 'Horticulture'), ('other', 'Other')], max_length=30)),
                ('variety', models.CharField(blank=True, max_length=150)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY_FOR_HARVEST', 'Ready for harvest'), ('HARVESTED', 'Harvested'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('land_preparation', 'Land preparation'), ('planting', 'Planting'), ('weeding', 'Weeding'), ('fertilization', 'Fertilization'), ('pest_control', 'Pest control'), ('irrigation', 'Irrigation'), ('harvesting', 'Harvesting'), ('other', 'Other')], max_length=30)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='farms.crop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('subcounty', models.CharField(blank=True, max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('size_unit', models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('square_meters', 'Square meters')], max_length=20)),
                ('farm_type', models.CharField(choices=[('crop_farming', 'Crop farming'), ('livestock', 'Livestock'), ('mixed_farming', 'Mixed farming'), ('poultry', 'Poultry farming'), ('fish_farming', 'Fish farming'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='farms.farm'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('size', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('size_unit', models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('square_meters', 'Square meters')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='farms.field'),
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.CheckConstraint(condition=models.Q(('size__gt', 0)), name='farm_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('size__gt', 0)), name='field_size_positive'),
        ),
    ]
