# Generated by Django 6.0.4 on 2026-09-15 12:35

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizer', 'Fertilizer'), ('Pesticides', 'Pesticides'), ('Labour', 'Labour'), ('Transport', 'Transport'), ('Equipment', 'Equipment'), ('Feed', 'Feed'), ('Veterinary', 'Veterinary'), ('Land preparation', 'Land preparation'), ('Other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='farms.farm')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('harvest_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='farms.farm')),
            ],
            options={
                'ordering': ['-harvest_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='harvest_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_contact', models.CharField(blank=True, max_length=50)),
                ('sale_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sale_total_non_negative')],
            },
        ),
    ]
