# Generated by Django 6.1.1 on 2026-09-15 17:07

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'market',
                'verbose_name_plural': 'markets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('price_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='markets.market')),
            ],
            options={
                'ordering': ['-price_date', '-id'],
                'indexes': [models.Index(fields=['market', 'price_date', 'product'], name='market_price_history_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='market_price_positive'), models.UniqueConstraint(fields=('market', 'product', 'price_date', 'unit'), name='unique_market_price_per_day')],
            },
        ),
    ]
